image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["License Apache 2.0", link="https://opensource.org/licenses/Apache-2.0"]
image:https://jitpack.io/v/aafwu00/netflix-evcache-spring.svg["Release", link=
"https://jitpack.io/#aafwu00/netflix-evcache-spring"]
image:https://circleci.com/gh/aafwu00/netflix-evcache-spring.svg?style=svg["CircleCI", link="https://circleci.com/gh/aafwu00/netflix-evcache-spring"]
image:https://app.fossa.io/api/projects/git%2Bgithub.com%2Faafwu00%2Fnetflix-evcache-spring.svg?type=shield["FOSSA Status", link="https://app.fossa.io/projects/git%2Bgithub.com%2Faafwu00%2Fnetflix-evcache-spring?ref=badge_shield"]
image:https://api.codacy.com/project/badge/Grade/7e1d4c8db17c47a591d98cd499a47b24["codacy", link="https://www.codacy.com/app/aafwu00/netflix-evcache-spring?utm_source=github.com&utm_medium=referral&utm_content=aafwu00/netflix-evcache-spring&utm_campaign=badger"]
image:https://codecov.io/gh/aafwu00/netflix-evcache-spring/branch/master/graph/badge.svg["codecov", link="https://codecov.io/gh/aafwu00/netflix-evcache-spring"]

= Netflix EVCache Spring

This project provides Netflix EVCache integrations for Spring Cache Abstraction, Spring Boot, Spring Cloud

== Getting Start

=== Prerequisites

=== Build
:jdkversion: 1.8

To build the source you will need to install JDK {jdkversion}.

----
$ ./gradlew build
----

=== Run memcached

start memcached server

[source,shell]
----
memcached -p 11211
memcached -p 11212
memcached -p 11213
memcached -p 11214
----

or run `docker-compose`

[source,shell]
----
docker-compose up
----

== Example

See on link:samples[samples]

=== evcache-spring

This project provides Netflix EVCache integrations for Spring Cache Abstraction.
See on link:samples/spring-sample[spring-sample]

1. Dependency Management

[source,gradle]
----
repositories {
    maven { url 'https://jitpack.io' } <1>
}

dependencies {
    compile 'com.github.aafwu00:evcache-spring:x.y.z' <2>
}
----
<1> add `jitpack` repository
<2> add dependency

2. Write java source code

[source,java]
----
@Configuration
@ComponentScan
@EnableCaching
public class TodoApp {
    @Bean
    public CacheManager cacheManager(final ConversionService conversionService) {
        EVCacheConfig.getInstance()
                     .getDynamicStringProperty("TODO-NODES",
                                               "shard1=localhost:11211,localhost:11212;shard2=localhost:11213,localhost:11214") # <2>
                     .get();
        final EVCacheConfiguration configuration = new EVCacheConfiguration();
        configuration.setName("todos");
        configuration.setTimeToLive(10);
        configuration.setServerGroupRetry(true);
        return new EVCacheManager("TODO", conversionService, Collections.singletonList(configuration)); # <1>
    }
}

@Repository
public class TodoRepository {
    @Cacheable(cacheNames = "todos", key = "'findAll'") # <3>
    public List<Todo> findAll() {
        return ...;
    }
}
----
<1> `EVCacheManager` app name is `TODO`
<2> `EVCacheManager` app name + `-NODES` means memcache server address, see on : https://github.com/Netflix/EVCache/wiki/Sample-EVCache-Deployment#step-4-create-a-cache-deployment-descriptor
<3> `@Cacheable` `cacheNames` is sames as `EVCacheConfiguration` name

=== evcache-spring-boot-starter

This project provides Netflix EVCache integrations for Spring Boot.
See on link:samples/spring-boot-sample[spring-boot-sample]

1. Dependency Management

[source,gradle]
----
repositories {
    maven { url 'https://jitpack.io' } <1>
}

dependencies {
    compile 'com.github.aafwu00:evcache-spring-boot-starter:x.y.z' <2>
}
----
<1> add `jitpack` repository
<2> add dependency

2. Write java code

[source,java]
----
@SpringBootApplication
@EnableCaching # <1>
public class Application {
    public static void main(final String[] args) {
        new SpringApplicationBuilder(Application.class).run(args);
    }
}

@Repository
public class TodoRepository {
    @Cacheable(cacheNames = "todos", key = "'findAll'") # <2>
    public List<Todo> findAll() {
        return ...;
    }
}
----
<1> see on https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/integration.html#cache
<2> `@Cacheable` `cacheNames` is sames as `evcache.prefixes[].name`

3. Write `application.yml` code, See on link:samples/spring-boot-sample/src/main/resources/config/application.yml[Sample]

[source,yml]
----
evcache:
  name: EVCACHE # <1>
  prefixes:
    - name: todos # <2>
      enable-exception-throwing: false

EVCACHE-NODES: shard1=localhost:11211,localhost:11212;shard2=localhost:11213,localhost:11214
----
<1> EVCache App Name
<2> EVCache cache name, cache prefix same as `@Cacheable` `cacheNames`
<3> `evcache.name` + `-NODES` means memcache server address, see on : https://github.com/Netflix/EVCache/wiki/Sample-EVCache-Deployment#step-4-create-a-cache-deployment-descriptor

IMPORTANT: `spring.cache.type` value is exists, evcache will be ignored


.Table EVCache Properties
|===
| Name | Default | Description

| evcache.enabled
| true
|

| evcache.name
|
| Name of the EVCache App cluster, Recommend Upper Case

| evcache.prefix[].name
|
| Cache name, Cache Prefix Key, Don't contain colon(:) character

| evcache.prefix[].timeToLive
| 900
| Default Time To Live(TTL), Seconds

| evcache.prefix[].allowNullValues
| true
| Whether to allow for `null` values

| evcache.prefix[].keyHash
| false
| Whether to convert key to hashing

| evcache.prefix[].serverGroupRetry
| true
| Retry across Server Group for cache misses and exceptions

| evcache.prefix[].enableExceptionThrowing
| false
| Exceptions are not propagated and null values are returned

| evcache.metrics.enabled
| true
| Spring Boot Metrics for EVCache

|===

See also: https://github.com/Netflix/EVCache/wiki/Configuring-EVCache-Client , https://github.com/Netflix/EVCache/blob/split/docs/config.md

=== evcar-spring-cloud-starter

WARNING: This project is not an original `EVCar`(`EVCache` + `Sidecar`).
EVCache Server composed `memcached` and `Prana`.
`EVCar` is not released at this time, so I combined the functions of `Eureka` + `Sidecar`.
You can find some hints about the function of `EVCar` below.

Hint on: https://github.com/Netflix/EVCache/issues/49 and https://github.com/Netflix/EVCache/tree/nflx-specific/evcar

Example EVCar, See on link:samples/evcar-sample[evcar-sample]

1. Start Eureka Server
See on link:samples/eureka-server-sample[eureka-server-sample]

2. Start memcached

3. Dependency Management

[source,gradle]
----
repositories {
    maven { url 'https://jitpack.io' } <1>
}

dependencies {
    compile 'com.github.aafwu00:evcar-spring-cloud-starter:x.y.z' <2>
}
----
<1> add `jitpack` repository
<2> add dependency

4. Write java source code

[source,java]
----
@SpringBootApplication
@EnableEVCar # <1>
public class Application {
    public static void main(final String[] args) {
        new SpringApplicationBuilder(Application.class).run(args);
    }
}
----
<1> Using `@EnableEVCar` annotation, that's all

5. Write `application.yml` code, See on link:samples/evcar-sample/src/main/resources/config/application.yml[Sample]

[source,yml]
----
spring:
  application:
    name: EVCACHE # <1>

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # <2>

evcar:
  port: 11211 # <3>
  group: shard1 # <4>
----
<1> EVCache App Name
<2> see on http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/1.4.0.RELEASE/multi/multi__service_discovery_eureka_clients.html#_registering_with_eureka
<3> memcached server port
<4> evcache server group, shard name of replica set

.Table EVCache Sidcar Properties
|===
| Name | Default | Description

| evcar.enabled
| true
|

| evcar.hostname
|
| Hostname of Memcached Or Rend, If blank using localhost

| evcar.port
| 11211
| Default Port of Memcached Or Rend

| evcar.group
| Default
| Server Group Name, shard name

| evcar.health.eureka.enabled
| true
| Eureka Health Check for Memcached

| evcar.metrics.enabled
| true
| Spring Boot Metrics for Memcached

| evcar.health.memcached.enabled
| true
| Spring Boot Health Check for Memcached

|===

=== evcache-spring-cloud-starter

This project provides Netflix EVCache And Eureka integrations for Spring Cloud.
see link:samples/spring-boot-sample[spring-boot-sample]

1. Run evcar.
See on <<evcar-spring-cloud-starter>>

2. Dependency Management

[source,gradle]
----
repositories {
    maven { url 'https://jitpack.io' } <1>
}

dependencies {
    compile 'com.github.aafwu00:evcache-spring-cloud-starter:x.y.z' <2>
}
----
<1> add `jitpack` repository
<2> add dependency

3. Write java code

[source,java]
----
@SpringBootApplication
@EnableDiscoveryClient # <1>
@EnableCaching # <2>
public class Application {
    public static void main(final String[] args) {
        new SpringApplicationBuilder(Application.class).run(args);
    }
}
----
<1> See on http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/1.4.0.RELEASE/multi/multi__service_discovery_eureka_clients.html#_registering_with_eureka
<2> See on https://docs.spring.io/spring-framework/docs/current/spring-framework-reference/integration.html#cache

4. Write `application.yml` code, See on link:samples/spring-cloud-sample/src/main/resources/config/application.yml[Sample]

[source,yml]
----
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # <1>

evcache:
  name: EVCACHE # <2>
  prefixes:
    - name: todos # <3>
      timeToLive: 5
      server-group-retry: true
----
<1> see on http://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/1.4.0.RELEASE/multi/multi__service_discovery_eureka_clients.html#_registering_with_eureka
<2> EVCache App Name(`spring.application.name`)
<3> EVCache cache name, cache prefix same as `@Cacheable` `cacheNames

IMPORTANT: `spring.cache.type` value is exists, evcache will be ignored

.Table EVCache Cloud Properties
|===
| Name | Default | Description

| evcache.cloud.enabled
| true
|

| evcache.cloud.nodeListMode
| `DataCenterAware`
| Support `EVCacheNodeList` mode for `Amazon`, `MyOwn`, `Simple` and `DataCenterAware`

| evcache.trace.enabled
| true
| Whether to use sleuth trace, If you want add dependency `spring-cloud-starter-sleuth`

|===

See also: https://github.com/Netflix/EVCache/wiki/Configuring-EVCache-Client , https://github.com/Netflix/EVCache/blob/split/docs/config.md , https://github.com/spring-cloud/spring-cloud-sleuth


== Contributing

Please read link:CONTRIBUTING.md[CONTRIBUTING.md] for details on our code of conduct, and the process for submitting pull requests to us.

== Versioning

We use http://semver.org/[SemVer] for versioning. For the versions available, see the link:https://github.com/aafwu00/netflix-evcache-spring/tags[tags on this repository].

== Authors

* **Taeho Kim** - *Initial work* - https://github.com/aafwu00[aafwu00]

== License

This project is licensed under the Apache License 2.0 - see the link:LICENSE[LICENSE] file for details

image:https://app.fossa.io/api/projects/git%2Bgithub.com%2Faafwu00%2Fnetflix-evcache-spring.svg?type=large["FOSSA Status", link="https://app.fossa.io/projects/git%2Bgithub.com%2Faafwu00%2Fnetflix-evcache-spring?ref=badge_large"]

== Acknowledgments

* https://github.com/Netflix/EVCache[EVCache]
* https://github.com/Netflix/EVCache/tree/nflx-specific/evcar[evcar]
* https://github.com/Netflix/eureka[Eureka]
* https://github.com/spring-projects/spring-boot[Spring Boot]
* https://github.com/spring-cloud/spring-cloud-netflix[Spring Cloud Netflix]
* http://nebula-plugins.github.io[Gradle Nebula Plugins]
