image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["License Apache 2.0", link="https://opensource.org/licenses/Apache-2.0"]
image:https://jitpack.io/v/aafwu00/netflix-evcache-spring.svg["Release", link=
"https://jitpack.io/#aafwu00/netflix-evcache-spring"]
image:https://circleci.com/gh/aafwu00/netflix-evcache-spring.svg?style=svg["CircleCI", link="https://circleci.com/gh/aafwu00/netflix-evcache-spring"]
image:https://app.fossa.io/api/projects/git%2Bgithub.com%2Faafwu00%2Fnetflix-evcache-spring.svg?type=shield["FOSSA Status", link="https://app.fossa.io/projects/git%2Bgithub.com%2Faafwu00%2Fnetflix-evcache-spring?ref=badge_shield"]
image:https://api.codacy.com/project/badge/Grade/7e1d4c8db17c47a591d98cd499a47b24["codacy", link="https://www.codacy.com/app/aafwu00/netflix-evcache-spring?utm_source=github.com&utm_medium=referral&utm_content=aafwu00/netflix-evcache-spring&utm_campaign=badger"]
image:https://codecov.io/gh/aafwu00/netflix-evcache-spring/branch/master/graph/badge.svg["codecov", link="https://codecov.io/gh/aafwu00/netflix-evcache-spring"]

= Netflix EVCache Spring

This project provides Netflix EVCache integrations for Spring Cache Abstraction, Spring Boot, Spring Cloud

== Getting Start

=== Prerequisites

=== Build
:jdkversion: 1.8

To build the source you will need to install JDK {jdkversion}.

----
$ ./gradlew build
----

=== Run memcached

start memcached server

[source,shell]
----
memcached -p 11211
memcached -p 11212
memcached -p 11213
memcached -p 11214
----

or run `docker-compose`

[source,shell]
----
docker-compose up
----

== Example

See on link:samples[samples]


include::evcache-client-spring/README.adoc[]

include::evcache-client-spring-boot-starter/README.adoc[]

include::evcache-server-spring-cloud-starter/README.adoc[]

include::evcache-client-spring-cloud-starter/README.adoc[]


== Contributing

Please read link:CONTRIBUTING.md[CONTRIBUTING.md] for details on our code of conduct, and the process for submitting pull requests to us.

== Versioning

We use http://semver.org/[SemVer] for versioning. For the versions available, see the link:https://github.com/aafwu00/netflix-evcache-spring/tags[tags on this repository].

== Authors

* **Taeho Kim** - *Initial work* - https://github.com/aafwu00[aafwu00]

== License

This project is licensed under the Apache License 2.0 - see the link:LICENSE[LICENSE] file for details

image:https://app.fossa.io/api/projects/git%2Bgithub.com%2Faafwu00%2Fnetflix-evcache-spring.svg?type=large["FOSSA Status", link="https://app.fossa.io/projects/git%2Bgithub.com%2Faafwu00%2Fnetflix-evcache-spring?ref=badge_large"]

== Acknowledgments

* https://github.com/Netflix/EVCache[EVCache]
* https://github.com/Netflix/EVCache/tree/nflx-specific/evcar[evcar]
* https://github.com/Netflix/eureka[Eureka]
* https://github.com/spring-projects/spring-boot[Spring Boot]
* https://github.com/spring-cloud/spring-cloud-netflix[Spring Cloud Netflix]
* http://nebula-plugins.github.io[Gradle Nebula Plugins]
