spring:
  application:
    name: todo

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

logging:
  level:
    root: info
    com.github.aafwu00: debug
    com.netflix: debug

evcache:
  name: evcache
  prefixes:
    - name: todos
      time-to-live: 5
      server-group-retry: true
      enable-exception-throwing: false

EVCACHE.use.inmemory.cache: true
EVCACHE.inmemory.cache.duration.ms: 1000
EVCACHE.log.operation.calls: SET,DELETE,GMISS,TMISS,BMISS_ALL,TOUCH,REPLACE
