spring:
  application:
    name: todo

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

evcache:
  clusters:
    TODO:
      app-name: EVCACHE
      key-prefix: todos
      time-to-live: 5s
      retry-enabled: true
      exception-throwing-enabled: false

EVCACHE.use.inmemory.cache: false
EVCACHE.inmemory.cache.duration.ms: 1000
EVCACHE.log.operation.calls: SET,DELETE,GMISS,TMISS,BMISS_ALL,TOUCH,REPLACE
