# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "evcache-client-spring/build.gradle" }}-{{ checksum "evcache-client-spring-boot-autoconfigure/build.gradle" }}-{{ checksum "evcache-client-spring-boot-starter/build.gradle" }}-{{ checksum "evcache-client-spring-cloud-autoconfigure/build.gradle" }}-{{ checksum "evcache-client-spring-cloud-starter/build.gradle" }}-{{ checksum "evcache-server-spring-cloud-autoconfigure/build.gradle" }}-{{ checksum "evcache-server-spring-cloud-starter/build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies--------

      - run: ./gradlew :evcache-client-spring-cloud-starter:dependencies :evcache-server-spring-cloud-starter:dependencies -Pexclude-ci

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "evcache-client-spring/build.gradle" }}-{{ checksum "evcache-client-spring-boot-autoconfigure/build.gradle" }}-{{ checksum "evcache-client-spring-boot-starter/build.gradle" }}-{{ checksum "evcache-client-spring-cloud-autoconfigure/build.gradle" }}-{{ checksum "evcache-client-spring-cloud-starter/build.gradle" }}-{{ checksum "evcache-server-spring-cloud-autoconfigure/build.gradle" }}-{{ checksum "evcache-server-spring-cloud-starter/build.gradle" }}

      # run tests!
      - run: ./gradlew check jacocoTestReport -Pexclude-ci

      # run codecov
      - run: bash <(curl -s https://codecov.io/bash)
