spring:
  application:
    name: todo

logging:
  level:
    root: info
    com.netflix: debug

evcache:
  clusters:
    - app-name: TODO
      key-prefix: todos
      time-to-live: 10s
      retry-enabled: true

TODO-NODES: shard1=localhost:11211
TODO.use.inmemory.cache: true
TODO.inmemory.cache.duration.ms: 1000
TODO.log.operation.calls: SET,DELETE,GMISS,TMISS,BMISS_ALL,TOUCH,REPLACE
