spring:
  application:
    name: todo

management:
  security:
    enabled: false

logging:
  level:
    root: info

evcache:
  clusters:
    - app-name: TODO
      cache-prefix: todos
      time-to-live: 10
      server-group-retry: true

TODO-NODES: shard1=localhost:11211
TODO.use.inmemory.cache: true
