spring:
  application:
    name: todo

management:
  security:
    enabled: false

logging:
  level:
    root: info

evcache:
  name: TODO
  prefixes:
    - name: todos
      time-to-live: 10
      server-group-retry: true


TODO-NODES: shard1=localhost:11211
TODO.use.inmemory.cache: true
