spring:
  application:
    name: evcache

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 11111

evcache:
  port: 11211
