spring:
  application:
    name: evcache

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

server:
  port: 11111

evcache:
  port: 11211

logging:
  level:
    root: info
    com.github.aafwu00: debug
    com.netflix: debug


